plugins:
  - jekyll-relative-links
theme: jekyll-theme-hacker
title: Go game for fun or boring
description: Go is Golang, not Go Chess.
author: Seapre
show_downloads: false
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  post_search: true